### ISSUE TITLE
No module named symeig

### ISSUE THREAD

**Issue by dheerajpai** [hq-jiang/instance-segmentation-with-discriminative-loss-tensorflow#4]
upon 
`/instance-segmentation-with-discriminative-loss-tensorflow ]$ python2 inference.py --modeldir trained_model --outdir inference_test/results`
I get the error:
```
Traceback (most recent call last):

  File "inference.py", line 12, in <module>
    from clustering import cluster, get_instance_masks, save_instance_masks
   from sklearn.cluster import MeanShift, estimate_bandwidth

  File "/usr/lib/python2.7/dist-packages/sklearn/cluster/__init__.py", line 6, in <module>
    from .spectral import spectral_clustering, SpectralClustering

  File "/usr/lib/python2.7/dist-packages/sklearn/cluster/spectral.py", line 17, in <module>
    from ..manifold import spectral_embedding

  File "/usr/lib/python2.7/dist-packages/sklearn/manifold/__init__.py", line 8, in <module>
    from .spectral_embedding_ import SpectralEmbedding, spectral_embedding

  File "/usr/lib/python2.7/dist-packages/sklearn/manifold/spectral_embedding_.py", line 12, in <module>
    from scipy.sparse.linalg.eigen.lobpcg.lobpcg import symeig

ImportError: cannot import name symeig
```

symeig is not a module in scipy.sparse.linalg.eigen.lobpcg.lobpcg. 

I guess there must be some edits required

**Comment by hq-jiang** [comment]
Maybe you could try this scipy==0.19.1 version? Unfortunately, I currently can't test without launching a AWS instance.
